### ISSUE TITLE
Nodes Panel throws error when refreshing

### ISSUE THREAD

**Issue by falkhofmann** [sisoe24/Nuke-Tools#5]
Hey Virgil,

first off many thanks for this collections of nuke helpers, sockets and other amazing things in this regard.

I wanted to finally try your vscode extension when working especially with blinkscript. but i ran into several issues which, i think, boiled it down to: that the Nodes panel is not working for me inside vscode.
i checked the NukeServerSocket connection and this seems all fine. tested receiver and all looks good to me. running python code also works from within vscode.

However, if i start a fresh connection inside nuke and want to refresh the Nodes panel in vscode, i get a short error message, but not really helping me to identify the actual issue.

`Unexpected token 'C', "Connected" is not valid JSON`

while i am not sure if thats THE issue i am having for running Blinkscript from within the IDE, its certainly an issue i do have.

below some screenshots from within nuke to give at least some details.

also FYI
i am running Linux Mint, Nuke 14.1v1 and got the latest release of the NukeServerSocket 0.6.1 (in the latest release the "wrong" version is stated in the .toml file [version = "0.6.0"]) 

![image](https://github.com/sisoe24/Nuke-Tools/assets/21419051/23cc4036-d572-42c8-adbf-36ba1a810bb8)

![image](https://github.com/sisoe24/Nuke-Tools/assets/21419051/d309660a-777c-4e56-9feb-261c8b816399)

If you have any idea on whats causing this, I would be delighted to finally use your extension at its full potential!

thank you sir,

Falk

**Comment by sisoe24** [comment]
Hey! Thank you for getting in touch and for pointing out that I forgot to update the poetry version to 0.6.1. I appreciate it!

Regarding your issue with the NodesPanel and BlinkScript node, if I understand correctly, you cannot use the NodesPanel with the BlinkScript node but can use it with Python nodes. If so, may I ask how you are using the NodesPanel? Do you have a BlinkScript node and want to "sync" the code to it? If that's what you're trying to do, it shouldn't work because the NodesPanel creates a PyScript_Knob under the hood to be used as a button.

The only way to use BlinkScript is by creating a file with an extension `.cpp` or `.blink`, and then sending the code with the `Nuke: Run Code Inside Nuke` command.

However, I'm trying to get the same error you have, but I can't. So maybe is a different error. I have created two short demos of some flows with both the node panel and BlinkScript. This should help us both to get a better understanding of the issue.

Basic NodesPanel flow
![basic_flow](https://github.com/sisoe24/Nuke-Tools/assets/28490646/4e753e2f-7636-4ff5-8541-c00a0ad15575)

BlinkScript (I am using the included sample snippet that comes with the suggestions)
![blink](https://github.com/sisoe24/Nuke-Tools/assets/28490646/d08d631a-0e45-4d3e-91c9-39d22179188d)

Let me know!

**Comment by sisoe24** [comment]
I may have found the issue. It seems to be related to a problem with json deserialization and serialization, which is potentially linked to the socket. When I initially obtain the nodes' name in Nuke's DAG, I serialize the socket data in the NodeTree. Following that, I parse the json data to construct the tree. The problem may arise during this process, since the JSON may not be properly deserialized due to the socket receiving a status message that reads "Connected" instead of the Nuke data.

likely the culprit
https://github.com/sisoe24/Nuke-Tools/blob/893ccdfe4ae4018578b5a1d99569c57474a110aa/src/nuke/nodes_tree.ts#L365C18-L365C18

I actually have a "Connected" string assigned to a status message, but it's only needed for tests. It shouldn't be a problem because once a connection is established, another call is made to the on-socket-data-ready function which overrides the message with the actual received data. 

It seems like in your case, the socket is stopping at the connected stage and skipping the received data. 

I also forgot to mention that there is a socket debug option in the settings. You could try activating it and trying again. We might get some more clues if I am on the right track.

**Comment by falkhofmann** [comment]
Hey,

Sorry, for the confusion on the issue. let me clear that up a bit.

- the connection is established between code and nuke. this does work fine. 
- running python code from vscode inside nuke works also fine
- the nodes panel in vscode does NOT show anything besides the refresh button. when i click on it, it does throw the error message. so far i could not use the NodesPanel
`Unexpected token 'C', "Connected" is not valid JSON`
- running blinkscript from within code does not work as in your demo. inside nuke ServerSocket UI, the status field shows "Message received" and in the received panel the Blinkscript code is also visible. But no node got created 
> that was my confusion, I thought i need to select a node in vscode node panel so nuke knows where to apply this sent blinkscript. but your demo helped to clear that up!
- I enabled the debug option but unfortunately there isn't much of output.

Blinkscript debug output
```

[2023-11-15T22:04:32.875Z] - Try connecting to 127.0.0.1:54331
[2023-11-15T22:04:32.876Z] - Connected.
[2023-11-15T22:04:32.876Z] - Message ready.
[2023-11-15T22:04:32.878Z] - Received: "Recompiling"

> Executing: /media/falk/data/vfx/projects/nuke_kombinat/dev_files/saturation.blink
Recompiling
[2023-11-15T22:04:32.879Z] - Connection ended.
[2023-11-15T22:04:32.879Z] - Connection closed. Had Errors: false

```


Python debug output
```

[2023-11-15T22:05:04.628Z] - Try connecting to 127.0.0.1:54331
[2023-11-15T22:05:04.629Z] - Connected.
[2023-11-15T22:05:04.629Z] - Message ready.
[2023-11-15T22:05:04.633Z] - Connection ended.
[2023-11-15T22:05:04.633Z] - Connection closed. Had Errors: false
```
but the blinkscript code arrives inside nuke

![image](https://github.com/sisoe24/Nuke-Tools/assets/21419051/e30ed410-afeb-4254-bfa6-d84a8ec550ba)


 - also I tried different Nuke versions but the issue persists.
 - i used the default saturation kernel to be sure that's not my own blinkscripts
 
 I am sorry for not being able to provide more data. Unfortunately I have no experience with sockets and therefore not much of a help. If i can do anything for testing to generate more debug data, let me know!
 
 thanks for getting back!
 Falk

**Comment by sisoe24** [comment]
Hmm, this is interesting. I'm thinking of trying it out on Linux Mint tomorrow, just to see if there's anything I've been taking for granted. However, let's focus on one thing at a time - the NodesPanel. To isolate the issue, I created a simple client socket sou you can test it outside vscode. You need `node.js` to run this script but otherwise you should be good to go. 

```js
/**
 * 1. Connect NukeServerSocket to port 54321
 * 2. Run this script with node.js
 *
 * The message is the python code to grab all nodes in the current Nuke script.
 * Once the message is received, it is parsed into a JSON object and printed to the console.
 * The problem appears to be that the message is not being sent back to the client.
 */
const net = require("net");

const HOST = "localhost";
const PORT = 54321;

// Create a new TCP client
const client = new net.Socket();

// Connect to the server
client.connect(PORT, HOST, () => {
    console.log("Connected to server");

    const message =
        "import nuke;import json;json.dumps({n.name():n.Class() for n in nuke.allNodes()})";
    client.write(message);

    client.end();
});

// Handle data from the server
client.on("data", (data) => {
    // This event is the one that receives from NukeServerSocket
    console.log("Received data:", data.toString());

    const receivedData = data.toString().replace(/'/g, "");
    
    // this is likely where the error `Unexpected token 'C', "Connected" is not valid JSON` happens
   // Althought it shouldnt happen now because there is no event status in this script.
    const toJSON = JSON.parse(receivedData);

    console.log("Received data:", toJSON);

    client.end();
});

client.on("close", () => {
    console.log("Connection closed");
});

client.on("error", (error) => {
    console.error("Error:", error.message);
});

```

The `toJSON` should be an object with all of the nodes inside your Nuke DAG. This is what output I got when testing mine
```
Connected to server
Received data: '{"RotoPaint1": "RotoPaint", "Grade2": "Grade"}'

Received data: { RotoPaint1: 'RotoPaint', Grade2: 'Grade' }
Connection closed
```

The extension socket is more complex with promises, so it may not provide a complete understanding, but it's a good starting point.

**Comment by falkhofmann** [comment]
hey there,
I installed Node.js and did a testrun. its actually straight forward on linux...
- i made sure the PORT is the same as in the script
- here is the result
```
node /home/falk/Desktop/socket_check.js 
Connected to server
Connection closed
```

as you can see there is not logged data. 
- i checked the output inside nuke on the widget. there is a status and message received. but the output is empty. so no nuke nodes are gathered. see lower screenshot attached
- i then tried to enter some more logging, to see, if the client.on("data"...) scope is actually entered. and it seems not. 

line30/31
```
console.log("enter client.on section");
console.log("Received data:", data.toString());
```
neither is logged and put into the console. so my feeling is, that its not the message which has issues, but the data handling. can that be the case? hard to describe without any node.js knowledge. but either the data is empty or the entire "section"/"scope" is not entered and therefore nothing is logged. but again, i dont know node.js nor socket management.
- to confirm: the actual json dumps snippet works as expected. i got all nodes listed if i run the line inside nuke.

nuke script editor after running the node.js script:
![image](https://github.com/sisoe24/Nuke-Tools/assets/21419051/db23c4fb-ce07-438d-89c5-e093b338a019)

NukeServerSocket widget after running the node.js script
![image](https://github.com/sisoe24/Nuke-Tools/assets/21419051/82abc5fa-d76b-459d-b8dc-7400f458c8a0)

hopefully there is some useful information for you. if i can test something else, let me know!

**Comment by sisoe24** [comment]
I have some good news! I installed Linux Mint as a virtual machine and ran into the same error that you had: "Unexpected token 'C', 'Connected' is not valid JSON". At least now I can reproduce the error, which means I can work on finding a solution. I plan to take a closer look at it this weekend.

By the way, are you also using a virtual machine?

**Comment by falkhofmann** [comment]
hey!
well that are indeed good news!
fingers crossed that you able to find the issue.
Personally i am running Mint for a long time on all my machines. Workstation, laptops etc. not as VM, just as a regular OS.

**Comment by sisoe24** [comment]
I found it! It has to do with the code execution engine used by NukeServerSocket. To fix it, you need to:

- Go to Settings and change the engine from Script Editor to Internal and then back to Script Editor again. This will ensure that the UI saves the configuration properly.

The reason why this happens is that NukeServerSocket defaults to the Internal engine even when the UI shows that the Script Editor is being used. This causes issues with the return value and can lead to errors. The Internal engine uses the `exec` function, which is known to cause problems. So, switching to Script Editor and back again will make sure that the configuration is saved correctly.

Let me know after you try

**Comment by falkhofmann** [comment]
hello sir!

this is it! 
everything works just fine for me now. Blinkscript creation inside Nuke as well as the Nodes Panel inside vscode. and of course combination of both together.
and i tried all other commands inside vscode as well. all up and running.

thank you very much for digging into the issue. its  very appreciated. truly.

feel free to close the issue from my side.

Thanks again!

**Comment by sisoe24** [comment]
Thank you for letting me know. I have made the update available. After updating NukeTools to the latest version (0.12.1), you can update NukeServerSocket to 0.6.2 with the command 'Nuke: Add NukeServerSocket'.
